/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MenuItem, Review } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // --- MENGJESI ---
  {
    id: 'mng_veze_sy',
    nameSq: 'Vezë Sy',
    nameEn: 'Sunny-Side Up Eggs',
    descriptionSq: 'Dy vezë në sy të gatuara me kujdes në gjalpë të freskët fshati.',
    descriptionEn: 'Two farm-fresh eggs fried sunny-side up in organic village butter.',
    price: 120,
    category: 'mengjesi',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'mng_omlet',
    nameSq: 'Omletë',
    nameEn: 'Omelette',
    descriptionSq: 'Omletë klasike e rrahur me erëza, gjalpë dhe djathtë të butë.',
    descriptionEn: 'Fluffy classic omelette prepared with savory herbs and local cheese.',
    price: 250,
    category: 'mengjesi',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUgTBh7eXH_tuHXCsSkxzwIMKWowS6gCPIkw&s',
  },
  {
    id: 'mng_veze_ziera',
    nameSq: 'Vezë të Ziera',
    nameEn: 'Boiled Eggs',
    descriptionSq: 'Dy vezë fshati të ziera sipas shijes suaj (të butë ose të forta).',
    descriptionEn: 'Two hard or soft boiled farm-fresh eggs cooked to your preference.',
    price: 100,
    category: 'mengjesi',
    image: 'https://shendeti.com.al/wp-content/uploads/2015/10/veze-te-ziera.jpg',
  },

  // --- MENGJESI ANGLEZ ---
  {
    id: 'mng_anglez',
    nameSq: 'Mëngjesi Anglez',
    nameEn: 'English Breakfast',
    descriptionSq: 'Omletë e pasur, salçiçe, proshutë, kërpudha, djathë i bardhë, kaçkavall, domate, kastravec.',
    descriptionEn: 'Hearty platter featuring an omelette, sausages, ham, mushrooms, white feta cheese, kashkaval, tomatoes, and cucumber.',
    price: 500,
    category: 'mengjesi_anglez',
    image: 'https://alsat.mk/wp-content/uploads/2021/09/mengjes-anglez.jpg',
  },

  // --- TAVA FAMILJARE ---
  {
    id: 'tav_fam_lazanje',
    nameSq: 'Lazanjë (Tavë Familjare)',
    nameEn: 'Family Lasagna Casserole',
    descriptionSq: 'Lazanjë e pasur me mish të grirë, salcë beshamel dhe djathë të shkrirë. Për 4-5 persona.',
    descriptionEn: 'Layered sheet pasta baked with rich ground beef ragù, creamy bechamel sauce, and gooey cheese. Serves 4-5.',
    price: 1800,
    category: 'tava_familjare',
    image: 'https://cdn.arteg.al/items/2023/dec/28/frwktjuuxf-2-thumb.png?1761296799',
  },
  {
    id: 'tav_fam_musaka',
    nameSq: 'Musaka (Tavë Familjare)',
    nameEn: 'Family Moussaka Casserole',
    descriptionSq: 'Shtresa patatesh, patëllxhanësh të pjekur, mishit të grirë dhe salcë beshamel të artë. Për 4-5 persona.',
    descriptionEn: 'Greek-style layered potatoes, roasted aubergines, flavor-packed minced meat, topped with rich bechamel. Serves 4-5.',
    price: 1800,
    category: 'tava_familjare',
    image: 'https://agroweb.org/wp-content/uploads/2018/03/musakaok.jpg',
  },
  {
    id: 'tav_fam_pastice',
    nameSq: 'Pastiçe (Tavë Familjare)',
    nameEn: 'Family Pastitsio Casserole',
    descriptionSq: 'Makaronat tona tradicionale të pjekura me qumësht, vezë të freskëta dhe djathë fshati. Për 4-5 persona.',
    descriptionEn: 'Baked pasta dish with organic milk, farm eggs, and traditional salted cheese. Serves 4-5.',
    price: 1200,
    category: 'tava_familjare',
    image: 'https://i.ytimg.com/vi/xemDmRviF_8/maxresdefault.jpg',
  },
  {
    id: 'tav_fam_jufka',
    nameSq: 'Jufka me Pulë (Tavë Familjare)',
    nameEn: 'Family Jufka with Chicken',
    descriptionSq: 'Jufka tradicionale dibrane, të pjekura në furrë me pulë të lëngshme dhe gjalpë zogu.',
    descriptionEn: 'Delicate hand-rolled traditional Albanian jufka pasta oven-baked with tender juicy chicken and village butter.',
    price: 1600,
    category: 'tava_familjare',
    image: 'https://i.ytimg.com/vi/J1F7FT-WAF4/sddefault.jpg',
  },
  {
    id: 'tav_fam_tave_kosi',
    nameSq: 'Tavë Kosi me Mish Qingji (Tavë Familjare)',
    nameEn: 'Family Lamb Tava Kosi Casserole',
    descriptionSq: 'Mish qingji tejet i butë, i pjekur me një salcë kremoze dhe delikate kosi e veze. Specialitet kombëtar.',
    descriptionEn: 'The pride of Albania: tender slow-baked spring lamb baked in a creamy yogurt, garlic, and egg sauce.',
    price: 2000,
    category: 'tava_familjare',
    image: 'https://www.artigatimit.com/wp-content/uploads/2013/02/tave-kosi-tave-elbasani-receta-gatimi-kuhzina-shqiptare-shije.jpg',
  },

  // --- PASTA / RIZOTO ---
  {
    id: 'pst_spaghetti_salce',
    nameSq: 'Spaghetti me Salcë',
    nameEn: 'Spaghetti Pomodoro',
    descriptionSq: 'Spageti të freskëta të shoqeruara me salcë domatesh të gatuar shtëpie dhe borzilok.',
    descriptionEn: 'Spaghetti tossed with slow-simmered homemade rich tomato marinara sauce and fresh basil.',
    price: 200,
    category: 'pasta_rizoto',
    image: 'https://www.deliciousmagazine.co.uk/wp-content/uploads/2024/09/2024D117_ITALIANSEO_POMODORO_2_X-1-768x960.jpg',
  },
  {
    id: 'pst_spaghetti_kim',
    nameSq: 'Spaghetti me Kim',
    nameEn: 'Spaghetti Bolognese',
    descriptionSq: 'Spageti me salcë mishi të grirë të gatuar gjatë me erëza, qepë dhe domate të freskëta.',
    descriptionEn: 'Classic spaghetti topped with slow-roasted minced beef, onions, aromatic herbs, and tomato ragù.',
    price: 300,
    category: 'pasta_rizoto',
    image: 'https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/easy_spaghetti_bolognese_93639_16x9.jpg',
  },
  {
    id: 'pst_pene_pana',
    nameSq: 'Pene Pana Proshutë',
    nameEn: 'Penne with Cream & Ham',
    descriptionSq: 'Pene kremoze të shoqëruara me pana cilësore, copëza proshute dhe piper të zi.',
    descriptionEn: 'Penne pasta in a luxurious cooking cream sauce with savory cured ham and cracked black pepper.',
    price: 250,
    category: 'pasta_rizoto',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwE6d8QExOhLpH0zlFY8-ziJ84DNQEN3wq3A&s',
  },
  {
    id: 'pst_pene_arrabiata',
    nameSq: 'Pene Arrabiata',
    nameEn: 'Penne All\'Arrabbiata',
    descriptionSq: 'Pene me salcë pikante domateje, spec djegës dhe vaj ulliri ekstra të virgjër.',
    descriptionEn: 'Penne pasta tossed in a robust, spicy tomato-chili sauce, garlic, and extra virgin olive oil.',
    price: 250,
    category: 'pasta_rizoto',
    image: 'https://www.giallozafferano.com/images/260-26061/Penne-all-arrabbiata_1200x800.jpg',
  },
  {
    id: 'pst_rizoto_perime',
    nameSq: 'Rizoto me Perime',
    nameEn: 'Vegetable Risotto',
    descriptionSq: 'Oriz arborio i gatuar me lëng perimesh dhe miks perimesh të stinës të freskëta.',
    descriptionEn: 'Arborio rice slowly cooked with rich vegetable broth and a colorful assortment of fresh seasonal vegetables.',
    price: 300,
    category: 'pasta_rizoto',
    image: 'https://cdnimpuls.com/living.al/images3/2018/maj/dhjetor18/kontrastet.jpg',
  },
  {
    id: 'pst_rizoto_pule',
    nameSq: 'Rizoto me Pulë',
    nameEn: 'Chicken Risotto',
    descriptionSq: 'Rizoto kremoze me mish pule të butë, kërpudha të freskëta dhe djathë parmesan.',
    descriptionEn: 'Creamy pan-seared risotto with tender chicken breast pieces, fresh mushrooms, and grated parmesan.',
    price: 350,
    category: 'pasta_rizoto',
    image: 'https://agroweb.org/wp-content/uploads/2022/01/orizz.jpg',
  },

  // --- GJELLE TE NDRYSHME ---
  {
    id: 'gjl_fasule',
    nameSq: 'Fasule',
    nameEn: 'Traditional White Beans',
    descriptionSq: 'Gjellë tradicionale me fasule të gatuara me qepë, speca, karota dhe erëza organike.',
    descriptionEn: 'A timeless Albanian comfort dish of white beans slow-cooked with fresh garden vegetables and mild paprika.',
    price: 150,
    category: 'gjelle_ndryshme',
    image: 'https://www.arise-app.com/images/dishes/en/white-bean-and-meat-stew-fasule-1dutxr.webp',
  },
  {
    id: 'gjl_bamje',
    nameSq: 'Bamje',
    nameEn: 'Okra Stew',
    descriptionSq: 'Bamje të freskëta të gatuara ngadalë në tavë me salcë domatesh, qepë dhe vaj ulliri.',
    descriptionEn: 'Tender baby okra stewed in a rich tomato, garlic, and roasted onion reduction.',
    price: 150,
    category: 'gjelle_ndryshme',
    image: 'https://i.ytimg.com/vi/lfgCGSF4oEY/maxresdefault.jpg',
  },
  {
    id: 'gjl_bizele',
    nameSq: 'Bizele',
    nameEn: 'Sweet Peas Stew',
    descriptionSq: 'Bizele të gatuara me rrush të butë karote dhe salcë delikate me barishte të freskëta.',
    descriptionEn: 'Sweet garden peas simmered in a light broth with carrots, potatoes, and fresh dill.',
    price: 150,
    category: 'gjelle_ndryshme',
    image: 'https://www.artigatimit.com/wp-content/uploads/2017/04/gjelle-shqip-bizele-patate-receta-gatimi-tradicionale-tigan.jpg',
  },
  {
    id: 'gjl_mashurka',
    nameSq: 'Mashurka',
    nameEn: 'Green Beans Stew',
    descriptionSq: 'Mashurka të gatuara në mënyrë shtëpiake, me pak domate dhe speca të ëmbël.',
    descriptionEn: 'Stewed green flat beans cooked till meltingly tender with fresh tomatoes and olive oil.',
    price: 150,
    category: 'gjelle_ndryshme',
    image: 'https://agroweb.org/wp-content/uploads/2018/05/mashurka-1.jpg',
  },
  {
    id: 'gjl_pace',
    nameSq: 'Paçe',
    nameEn: 'Traditional Pace Soup',
    descriptionSq: 'Paçe tradicionale e trashë me mish koke, e zier ngadalë me hudhër, limon dhe piper të kuq.',
    descriptionEn: 'Rich and traditional slow-simmered bone-broth meat soup seasoned with fresh garlic, vinegar, and red pepper.',
    price: 250,
    category: 'gjelle_ndryshme',
    image: 'https://www.balkanweb.com/wp-content/uploads/2019/01/pace-koke.jpg',
  },
  {
    id: 'gjl_tasqebap',
    nameSq: 'Tasqebap',
    nameEn: 'Tasqebap Beef Stew',
    descriptionSq: 'Mish viçi i skuqur me qepë, hudhra, dafinë, i shuar me verë dhe i gatuar derisa të shkrihet.',
    descriptionEn: 'An authentic Albanian pan-dish of tender hand-cut beef stewed with white wine, garlic, and bay leaves.',
    price: 250,
    category: 'gjelle_ndryshme',
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Tasqebap.jpg',
  },
  {
    id: 'gjl_mish_jani',
    nameSq: 'Mish Jani',
    nameEn: 'Mish Jani Onion Beef Stew',
    descriptionSq: 'Gjellë unike tradicionale me mish viçi dhe sasi të bollshme qepësh të karamelizuara e erëzash.',
    descriptionEn: 'Rich local beef stew packed with sweet caramelized onions, red pepper flakes, and warm traditional spices.',
    price: 250,
    category: 'gjelle_ndryshme',
    image: 'https://agroweb.org/wp-content/uploads/2018/09/jahni_speciale901.jpg',
  },

  // --- SUPA ---
  {
    id: 'sup_magjiric',
    nameSq: 'Supë Magjiriç',
    nameEn: 'Traditional Magjiric Soup',
    descriptionSq: 'Supë tradicionale elbasanase, e pasur me lëng mishi taze, barishte dhe e trashur me vezë e limon.',
    descriptionEn: 'Traditional rich herbal broth and chopped lamb soup finished with a whipped egg-lemon emulsion.',
    price: 200,
    category: 'supa',
    image: 'https://cdnimpuls.com/the-living-media.com/media3/-640-0-6266b17d04f59.jpg',
  },
  {
    id: 'sup_pule',
    nameSq: 'Supë Pule',
    nameEn: 'Chicken Soup',
    descriptionSq: 'Supë e lehtë me lëng pule të freskët, fije mishi pule, makarona të vogla (ose oriz) dhe limon.',
    descriptionEn: 'Soothing classic chicken noodle soup with shredded poultry, garden herbs, and organic lemon juice.',
    price: 200,
    category: 'supa',
    image: 'https://mediterraneanlatinloveaffair.com/wp-content/uploads/2019/10/Supe-pule-limon-Chicken-lemon-Soup.jpg',
  },
  {
    id: 'sup_dites',
    nameSq: 'Supë e Ditës',
    nameEn: 'Soup of the Day',
    descriptionSq: 'Supë sezonale e sapopërgatitur nga kryekuzhinieri ynë me përbërës të freskët tregu.',
    descriptionEn: 'Daily fresh, handcrafted soup created by our chef using today’s premium local harvest.',
    price: 200,
    category: 'supa',
    image: 'https://www.kosova-sot.info/uploads/kosova-sot/images/2023/October/30/auto_auto_supe16354037211698655906.jpg',
  },

  // --- SHOQERUESE ---
  {
    id: 'shq_pilaf',
    nameSq: 'Pilaf',
    nameEn: 'Pilaf Rice',
    descriptionSq: 'Oriz i gatuar me lëng mishi taze dhe i spërkatur me gjalpë të freskët fshati.',
    descriptionEn: 'Fluffy white rice cooked in fresh rich broth, finished with browned country butter.',
    price: 80,
    category: 'shoqeruese',
    image: 'https://chefoodrevolution.com/wp-content/uploads/turkish-rice-pilaf.webp',
  },
  {
    id: 'shq_patate_skuqura',
    nameSq: 'Patate të Skuqura',
    nameEn: 'French Fries',
    descriptionSq: 'Patate të skuqura të freskëta, krokante nga jashtë e të buta brenda, me pak rigon sipër.',
    descriptionEn: 'Crispy skin-on golden french fries hand-cut daily and sprinkled with mountain oregano.',
    price: 150,
    category: 'shoqeruese',
    image: 'https://argjiroja.net/wp-content/uploads/2020/05/67a254d5eb9fc0e2976618499038d462.jpg',
  },
  {
    id: 'shq_patate_furre',
    nameSq: 'Patate Furre',
    nameEn: 'Roasted Oven Potatoes',
    descriptionSq: 'Patate të prera me feta të pjekura në furrë me vaj ulliri, hudhra, rozmarinë dhe limon.',
    descriptionEn: 'Thick wedges of seasoned potatoes roasted in the oven with olive oil, rosemary, and lemon juice.',
    price: 200,
    category: 'shoqeruese',
    image: 'https://admin.albanianpost.com/wp-content/uploads/2021/12/9ff69c04442b40637c1be5fbae26c1ec_header.jpg',
  },
  {
    id: 'shq_djath_bardh',
    nameSq: 'Djatht i Bardhë',
    nameEn: 'White Feta Cheese Portion',
    descriptionSq: 'Porcion djathi tradicional të bardhë, i kripur dhe i pasur, nga stanet e zonës.',
    descriptionEn: 'A healthy slab of traditional local white cheese sourced from sheep of Albanian pastures.',
    price: 100,
    category: 'shoqeruese',
    image: 'https://abcnews.al/wp-content/uploads/2020/08/Peysah1.jpg',
  },
  {
    id: 'shq_djath_kackavall',
    nameSq: 'Djath Kaçkavall',
    nameEn: 'Kashkaval Cheese Portion',
    descriptionSq: 'Djathë kaçkavall shqiptar i fortë dhe tejet i shijshëm, ideal si shoqërues.',
    descriptionEn: 'A portion of semi-hard traditional Albanian cows milk kashkaval cheese.',
    price: 120,
    category: 'shoqeruese',
    image: 'https://baronesha.al/wp-content/uploads/2024/10/Untitled_design_-_2023-01-20T093839.932.png',
  },
  {
    id: 'shq_perime_zgare',
    nameSq: 'Perime Zgare',
    nameEn: 'Grilled Vegetables',
    descriptionSq: 'Kunguj, patëllxhanë, speca, qepë dhe kërpudha të gatuara në skarë me vaj ulliri dhe uthull balsamike.',
    descriptionEn: 'Char-grilled zucchini, eggplants, bell peppers, onions, and mushrooms drizzled with olive oil and vinegar.',
    price: 200,
    category: 'shoqeruese',
    image: 'https://agroweb.org/wp-content/uploads/2018/01/okperimetepjekura.jpg',
  },
  {
    id: 'shq_perime_furre',
    nameSq: 'Perime Furre',
    nameEn: 'Roasted Oven Vegetables',
    descriptionSq: 'Perime të ndryshme stine të pjekura ngadalë në furrë me barishte aromatikë.',
    descriptionEn: 'Mixed seasonal country vegetables baked in olive oil and sweet rustic Mediterranean spices.',
    price: 250,
    category: 'shoqeruese',
    image: 'https://pernenat.al/wp-content/uploads/2016/03/veg33.jpg',
  },
  {
    id: 'shq_kos',
    nameSq: 'Kos',
    nameEn: 'Village Yogurt Portion',
    descriptionSq: 'Kos i trashë fshati, i freskët dhe pa konservantë, i pasur në vlera.',
    descriptionEn: 'Thick, creamy local sour yogurt, 100% natural, sourced directly from artisanal dairies.',
    price: 80,
    category: 'shoqeruese',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNkwReIsqz1sSdouGYsIDmZvtlzOsRjwSBqA&s',
  },
  {
    id: 'shq_tarator',
    nameSq: 'Tarator',
    nameEn: 'Tarator',
    descriptionSq: 'Kos i rrahur me pak ujë, copa trangujsh, hudhër, vaj ulliri dhe kopër të freskët.',
    descriptionEn: 'Chilled creamed yogurt soup mixed with diced crunchy cucumbers, crushed garlic, and aromatic dill.',
    price: 80,
    category: 'shoqeruese',
    image: 'https://img.sndimg.com/food/image/upload/q_92,fl_progressive,w_1200,c_scale/v1/img/recipes/62/18/1/pic0pkinL.jpg',
  },

  // --- SALLATA ---
  {
    id: 'sal_cezar',
    nameSq: 'Sallatë Cezar',
    nameEn: 'Caesar Salad',
    descriptionSq: 'Maratë krokante, fileto pule në skarë, krotone, parmesan dhe salca jonë unike Cezar.',
    descriptionEn: 'Crisp romaine lettuce, premium grilled chicken, golden garlic croutons, dynamic parmesan shavings and Caesar dressing.',
    price: 350,
    category: 'sallata',
    image: 'https://www.kosova-sot.info/uploads/kosova-sot/images/2021/October/13/auto_Tortellini-Caesar-Salad-3-500x5001634106604.jpg',
  },
  {
    id: 'sal_fshati',
    nameSq: 'Sallatë Fshati',
    nameEn: 'Village Salad',
    descriptionSq: 'Domate, kastravecë, speca, qepë, ullinj, me një fetë djathë të bardhë sipër dhe oregano.',
    descriptionEn: 'Traditional Greek/Village style salad with vine-ripe tomatoes, cucumbers, olives, onions, olive oil, and feta.',
    price: 200,
    category: 'sallata',
    image: 'https://panairionline.com/menu/600-sallate.jpg',
  },
  {
    id: 'sal_miks',
    nameSq: 'Sallatë Miks',
    nameEn: 'Mixed Garden Salad',
    descriptionSq: 'Miks sallatash jeshile, karotë e grirë, lakër e kuqe e bardhë, e spërkatur me limon e vaj ulliri.',
    descriptionEn: 'Healthy green leaf salad featuring shredded carrots, red cabbage, and fresh vinaigrette dressing.',
    price: 200,
    category: 'sallata',
    image: 'https://i.ytimg.com/vi/AeimZWdHprk/mqdefault.jpg',
  },

  // --- TAVA TRADICIONALE ---
  {
    id: 'tav_trd_fergese',
    nameSq: 'Fergesë Tiranë',
    nameEn: 'Tirana Style Fergese',
    descriptionSq: 'Speca, qepë dhe domate të ziera dhe të pjekura në enë balte me gjizë e gjalpë të ngrohtë.',
    descriptionEn: 'A savory baked claypot delicacy of creamed cottage cheese, sweet peppers, garlic, and fresh tomatoes.',
    price: 300,
    category: 'tava_tradicionale',
    image: 'https://scontent.xx.fbcdn.net/v/t1.15752-9/722808513_1919120355592594_7235818657223826191_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=fc17b8&_nc_ohc=qg1hE-rxPrkQ7kNvwFEMtRU&_nc_oc=Adr5D4dBTzb9wH4R-NtwSIb5jDwR036ITxf8CFrjEqRILzBr1NPYqdGDksu43L-n5PqdfQc8E4PCecBaNvAwZxx6&_nc_ad=z-m&_nc_cid=0&_nc_zt=23&_nc_ht=scontent.xx&oh=03_Q7cD5gFahIhm6dRDVVTtUxkr4guQERr8Az-1Fu5L6rHNNEIAVA&oe=6A525010',
  },
  {
    id: 'tav_trd_tave_kosi',
    nameSq: 'Tavë Kosi me Mish Qingji',
    nameEn: 'Individual Lamb Tava Kosi',
    descriptionSq: 'Mish qingji tejet i butë fshati, i gatuar me kos të thartë e vezë në enë balte individuale.',
    descriptionEn: 'Individual claypot baked savory spring lamb in Elbasan-style thick set egg and yogurt sauce.',
    price: 300,
    category: 'tava_tradicionale',
    image: 'https://scontent.xx.fbcdn.net/v/t1.15752-9/720327895_1314831280265103_5439644534657480866_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=fc17b8&_nc_ohc=kJ3lmNullGMQ7kNvwGF95jH&_nc_oc=Adp-LLurQ_M_0KkLN0ifTbauhbRahQTFTDSrHajkLgZC-xLSTsh_MKXR_6ZnDGiVFCgkCXeT-UObkBkWuxuiE9Mh&_nc_ad=z-m&_nc_cid=0&_nc_zt=23&_nc_ht=scontent.xx&oh=03_Q7cD5gEoeE9upw7X_oeuAm_ia0C0HYot3ifEh8bdppIZOK613A&oe=6A523B7D',
  },
  {
    id: 'tav_trd_gjuveci_mish',
    nameSq: 'Tavë Gjuveci me Mish',
    nameEn: 'Claypot Beef Stew (Gjuvec)',
    descriptionSq: 'Gjuveç i veçantë me perime stine të përzgjedhura dhe mish viçi të butë, pjekur në baltë.',
    descriptionEn: 'Rustic claypot casserole slow baking tender beef with seasonal roots, peas, and rich tomato glaze.',
    price: 300,
    category: 'tava_tradicionale',
    image: 'https://shqiptarja.com/uploads/780x440/1669585939_maxresdefault.jpg',
  },
  {
    id: 'tav_trd_gjuveci_pule',
    nameSq: 'Tavë Gjuveci me Pulë',
    nameEn: 'Claypot Chicken Stew (Gjuvec)',
    descriptionSq: 'Tavë gjuveçi me copëza pule të shijshme e lëng, e pjekur me oriz dore ose me gjuveç perimesh.',
    descriptionEn: 'Savory slow-baked chicken stew with colorful vegetables and herbs baked inside an artisanal clay vessel.',
    price: 300,
    category: 'tava_tradicionale',
    image: 'https://i.ytimg.com/vi/BxMOII_LrY4/maxresdefault.jpg',
  },
  {
    id: 'tav_trd_speca_mbushura',
    nameSq: 'Speca të Mbushura',
    nameEn: 'Stuffed Bell Peppers',
    descriptionSq: 'Speca të pjekur të mbushur me oriz të aromatizuar, mish të grirë dhe barishte të freskëta.',
    descriptionEn: 'Sweet bell peppers stuffed with herb-spiced rice, minced beef, and baked to tender perfection.',
    price: 200,
    category: 'tava_tradicionale',
    image: 'https://scontent.xx.fbcdn.net/v/t1.15752-9/722296223_1475210330575675_6015863741940729769_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=fc17b8&_nc_ohc=tX6dZwr68EAQ7kNvwFd8VrL&_nc_oc=AdrA-JDOrKDV50W9uNsCeLN65DRn4rPcrV9Pmxrf70p4F4TUtCWJmm5CLWz4S9wkiMK0GodakTFssGD7rChmvCD8&_nc_ad=z-m&_nc_cid=0&_nc_zt=23&_nc_ht=scontent.xx&oh=03_Q7cD5gGkgPK54oo5AvIh0YpaVrhNkiGXIDfLbfzs10vmowxdjw&oe=6A5230BE',
  },
  {
    id: 'tav_trd_patellxhan',
    nameSq: 'Patëllxhan të Mbushur',
    nameEn: 'Stuffed Baked Eggplates',
    descriptionSq: 'Patëllxhanë të pjekur të mbushur me qepë të skuqura, domate, erëza dhe hudhër.',
    descriptionEn: 'Traditional baked baby eggplants stuffed with aromatic garlic, slow-reduced tomatoes and onions.',
    price: 200,
    category: 'tava_tradicionale',
    image: 'https://images.unsplash.com/photo-1518779578993-ec3579fee39f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'tav_trd_pastico',
    nameSq: 'Pastiço',
    nameEn: 'Baked Pastico (Individual)',
    descriptionSq: 'Porcion individual e pastiçes klasike me makarona, qumësht, vezë të cilësisë së parë dhe djathë.',
    descriptionEn: 'Individual portion of golden baked macaroni pie with wholesome milk, eggs, and soft white cheese.',
    price: 200,
    category: 'tava_tradicionale',
    image: 'https://mediterraneanlatinloveaffair.com/wp-content/uploads/2019/11/Baked-pasta-feta-cheese-eggs-fettuccine.jpg',
  },
  {
    id: 'tav_trd_musaka',
    nameSq: 'Musaka (Porcion)',
    nameEn: 'Baked Moussaka (Individual)',
    descriptionSq: 'Musaka shtëpie e pjekur në furrë me shtresa patatesh e mishi të grirë.',
    descriptionEn: 'Oven-baked traditional moussaka portion with rich potato base layers and spiced ground meat.',
    price: 300,
    category: 'tava_tradicionale',
    image: 'https://assets.ichkoche.at/image/17/165335.jpg?v=2&twic=v1/focus=50px50p/cover=496x384',
  },
  {
    id: 'tav_trd_lazanje',
    nameSq: 'Lazanjë (Porcion)',
    nameEn: 'Baked Lasagna (Individual)',
    descriptionSq: 'Shtresa makaronash të holla të mbushura me ragu mishi, beshamel, dhe parmesan të pjekur.',
    descriptionEn: 'Golden, melting, multi-layered delicious pasta sheets layered with dynamic meaty ragu and bechamel.',
    price: 300,
    category: 'tava_tradicionale',
    image: 'https://www.simplyrecipes.com/thmb/KZei8Ydgfmh_cdomk3RfpG3Z-rw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Best-Homemade-Lasagna-LEAD-4-7cb54b4d2b264bb3a2b4fbdb85e90d22.jpg',
  },
  {
    id: 'tav_trd_qofte_korce',
    nameSq: 'Tavë me Qofte Korçe me Salcë',
    nameEn: 'Korca Meatballs in Sauce',
    descriptionSq: 'Qofte tradicionale korçare të pjekura në enë balte me salcë pikante shtëpie dhe dhjamë.',
    descriptionEn: 'Gently spiced Korca meatballs simmered and baked in rich claypot tomato-garlic reduction.',
    price: 300,
    category: 'tava_tradicionale',
    image: 'https://www.artigatimit.com/wp-content/uploads/2017/02/kernacka-korce-kuzhina-shqiptare-receta-gatimi-arti-gatimit.jpg',
  },

  // --- ZGARE ---
  {
    id: 'zgr_qofte_shtepi',
    nameSq: 'Qofte Shtëpie (copë)',
    nameEn: 'Homemade Grilled Meatball (piece)',
    descriptionSq: 'Qofte e sapopjekur në skarë, sipas recetës së vjetër shtëpiake me erëza e hudhër.',
    descriptionEn: 'Single piece of grilled traditional skinless beef meatball spiked with family seasoning.',
    price: 80,
    category: 'zgare',
    image: 'https://aljeta.com/wp-content/uploads/2024/05/Qofte-De-albanese-gehaktbal.jpg',
  },
  {
    id: 'zgr_brinje_qingji',
    nameSq: 'Brinjë Qingji',
    nameEn: 'Grilled Lamb Ribs',
    descriptionSq: 'Brinjë të freskëta qingji të pjekura në skarë qymyri derisë të bëhen krokante e të lëngshme.',
    descriptionEn: 'Tender marinated baby lamb bone-in ribs grilled over hot coals to crispy perfection.',
    price: 300,
    category: 'zgare',
    image: 'https://www.artigatimit.com/wp-content/uploads/2012/04/brinje-qengji-ne-zgare.jpg',
  },
  {
    id: 'zgr_berxolle_vici',
    nameSq: 'Bërxhollë Viçi',
    nameEn: 'Grilled Veal Chop',
    descriptionSq: 'Bërxhollë e freskët viçi e pjekur në skarë nxehtë me kripë deti e limon.',
    descriptionEn: 'Thick marinated succulent veal chop flame-grilled, served with a fresh lemon wedge.',
    price: 300,
    category: 'zgare',
    image: 'https://era.al/wp-content/uploads/2022/11/BABON-1-25.jpg',
  },
  {
    id: 'zgr_biftek_vici',
    nameSq: 'Biftek Viçi',
    nameEn: 'Grilled Veal Steak',
    descriptionSq: 'Biftek viçi i zgjedhur, i rrahur me kujdes dhe i pjekur në çast sipas dëshirës.',
    descriptionEn: 'Selected premium sliced lean beef steak cooked juicy on the flat top grill.',
    price: 300,
    category: 'zgare',
    image: 'https://era.al/wp-content/uploads/2022/11/BABON-1-39.jpg',
  },
  {
    id: 'zgr_sunxhuk',
    nameSq: 'Sunxhuk',
    nameEn: 'Grilled Sudjuk Sausage',
    descriptionSq: 'Suxhuk tradicional i thatë e me erëza djegëse, i pjekur në skarë të nxehtë.',
    descriptionEn: 'Thick cut spicy garlic dried beef sausage grilled to extract maximum smoky aroma.',
    price: 200,
    category: 'zgare',
    image: 'https://itscraft.com.ua/content/images/36/1000x667l80nn0/61752420657629.jpeg',
  },
  {
    id: 'zgr_llukanik',
    nameSq: 'Llukanik',
    nameEn: 'Traditional Sausage (Llukanik)',
    descriptionSq: 'Suxhuk i butë tradicional i pjekur shkëlqyeshëm në skarë me barishte organike.',
    descriptionEn: 'Mild, rich, traditional country-style pork sausage roasted to juicy perfection.',
    price: 200,
    category: 'zgare',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrKUn-WIppOs5yIFGAacT56juf03voebchKg&s',
  },
  {
    id: 'zgr_fileto_pule',
    nameSq: 'Fileto Pule',
    nameEn: 'Grilled Chicken Fillet',
    descriptionSq: 'Gjoks pule i marinuar me qumësht, hudhra, dhe vaj ulliri, e pjekur me kujdes.',
    descriptionEn: 'Marinated tender chicken breast fillet grilled moist and flavorful on the chargrill.',
    price: 250,
    category: 'zgare',
    image: 'https://orarvcamping.al/images/detailed/12/Untitled_design_-_2023-01-26T103902.196.png',
  },
  {
    id: 'zgr_pule_zgare',
    nameSq: 'Pulë Zgare (me peshë)',
    nameEn: 'Whole Grilled Chicken (by weight)',
    descriptionSq: 'Pulë fshati e sapomarinuar e pjekur ngadalë e tërë në skarë. Çmimi llogaritet për KG.',
    descriptionEn: 'Marinated whole premium village chicken slowly rotated and flame-grilled. Price is calculated per KG.',
    price: 600,
    category: 'zgare',
    image: 'https://www.recetakuzhine.net/wp-content/uploads/2016/02/pulenezgar.jpg',
    isByKg: true,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    author: 'Xhorxhia Behaj',
    rating: 5,
    timeSq: '7 muaj më parë',
    timeEn: '7 months ago',
    textSq: 'E rekomandoj plotësisht! Ushqim i shkëlqyer i përgatitur me përbërës të freskët, shumë i shijshëm. Shërbim jashtëzakonisht i mirë gjithashtu.',
    textEn: 'I totally recommend! Great food made with fresh ingredients, very tasteful. Very good service as well.',
    avatarColor: '#E07A2E',
  },
  {
    id: 'rev_2',
    author: 'arla lleshaj',
    rating: 5,
    timeSq: '7 muaj më parë',
    timeEn: '7 months ago',
    textSq: 'Ushqim i mrekullueshëm dhe shërbim i shkëlqyer! E rekomandoj me shumë forcë.',
    textEn: 'Amazing food and excellent service! Highly recommend.',
    avatarColor: '#799F64',
  },
  {
    id: 'rev_3',
    author: 'Edesa Behaj',
    rating: 5,
    timeSq: '7 muaj më parë',
    timeEn: '7 months ago',
    textSq: 'Ushqim tradicional Shqiptar i gatuar me pasion. Ushqimi është jashtëzakonisht i shijshëm.',
    textEn: 'Traditional Albanian food. The food is delicious. Absolute five stars!',
    avatarColor: '#FCD581',
  },
  {
    id: 'rev_4',
    author: 'Drilon K.',
    rating: 4,
    timeSq: '2 javë më parë',
    timeEn: '2 weeks ago',
    textSq: 'Jemi duke shijuar ushqimin këtu rregullisht. Çdo gjë është taze, ashtu siç gatuhet në shtëpi. Çmimet janë fantastike.',
    textEn: 'We enjoy the food here regularly. Everything is fresh, exactly like what you cook at home. The prices are fantastic.',
    avatarColor: '#DCE3EB',
  },
];
